version: "3.0"
services:
  redis:
    image: "redis:alpine"
    command: redis-server /usr/local/etc/redis/redis.conf --loglevel verbose
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/usr/local/etc/redis
    networks:
      - pubsub

  pub:
    build:
      context: ./pub
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - pubsub
  sub:
    build:
      context: ./sub
      dockerfile: Dockerfile
    depends_on:
      - redis
      - pub
    networks:
      - pubsub

networks:
  pubsub:
    driver: bridge
